<?php

require 'plugins/sfOauthPlugin/lib/model/om/BaseSfApplicationPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'sf_application' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Mon Mar  1 13:53:16 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.sfOauthPlugin.lib.model
 */
class SfApplicationPeer extends BaseSfApplicationPeer {

} // SfApplicationPeer
