default:
  components:
    sparkline:  [general, sparkline]
    subreviews:  [sfReviewFront, subreviews]
    review_list:  [sfReviewFront, reviewList]
    quickvote:  [sfReviewFront, quickvote]
    tags:  [general, tags]
    tagList:  [general, tagList]
    sendStmt:   [sfReviewFront, sendStmt]
    sfrForm:  [sfReviewFront, sfrForm]
    sfrPreview:  [sfReviewFront, sfrPreview]
    
all:
  javascripts: 
    