rendering: ~

facebook_connect:
  class: sfFacebookConnectFilter
  enabled: false	
remember_me:
  class: sfGuardRememberMeFilter
security:
  class: voSecurityFilter
  
culture:
  class: voCultureFilter
  enabled: false	
redirect:
  class: voRedirectFilter
  enabled: false	
vobase:
  class: voBaseFilter
  enabled: false	
browser:
  class: voBrowserFilter
  enabled: false	


cache:     ~
common:
  class: sfCommonFilter
execution: ~
