default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, ui-lightness/jquery-ui-1.7.2.custom.css, ../sfPropelPlugin/css/global.css, ../sfPropelPlugin/css/default.css]

  javascripts: [jquery-1.3.2.min.js, jquery-ui-1.7.2.custom.min.js]

  has_layout:     true
  layout:         layout
