generator:
  class: sfPropelGenerator
  param:
    model_class:           Partido
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          partido
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        title:   Partidos
        display: [nombre,abreviatura,color,web,imagen]
          
      filter:  ~
      form:
        display:
          "Datos Partido": [nombre,abreviatura,color,web,imagen]
      edit:
        title:   Partido

      new:
        title:   Nuevo partido
