generator:
  class: sfPropelGenerator
  param:
    model_class:           Partido
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          partido
    with_propel_route:     1

    config:
      actions: ~
      fields:
        is_main:
          label: Aparece en el listado principal
      list:
        title:   Partidos
        display: [nombre,abreviatura,color,imagen, is_active]
          
      filter:  ~
      form:
        display:
          "Datos Partido": [abreviatura,color,is_active, is_main,imagen]
          "Traducibles": [es,ca]
          "Enlaces": []
      edit:
        title:   Partido

      new:
        title:   Nuevo partido
