generator:
  class: sfPropelGenerator
  param:
    model_class:           Convocatoria
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Convocatoria
    plural:                Convocatorias
    route_prefix:          convocatoria
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:   convocatorias
        display: [id,eleccion,nombre,fecha]
      filter:  ~
      form:    
        display:
          "Datos generales": [id,nombre,eleccion_id,fecha,imagen]
          "Traducibles": [es,ca]
          "Enlaces": []
      edit:    ~
      new:     ~
