default:
  components:
    propuestaResult:  [general, propuestaResult]
    politicoResult:  [general, politicoResult]
    partidoResult:  [general, partidoResult]
    institucionResult:  [general, institucionResult]
    usuarioResult:  [general, usuarioResult]
    tagList:  [general, tagList]
    