<?php

require 'lib/model/om/BasePropuestaPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'propuesta' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Fri Apr  9 16:18:01 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class PropuestaPeer extends BasePropuestaPeer {

	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		$cache = sfcontext::getInstance()->getViewCacheManager()->getCache();
	  	if ($cache != null) {
			$cacheKey = "pro_count";
			foreach($criteria->keys() as $key){
				$cacheKey .= "_$key";
			}
	  		$key=md5($cacheKey);
  			$data = $cache->get($key);
	  	}
	  	else {
	  		$data = false;
	  	}
  		if ($data){	
  			return unserialize($cache->get("$key"));  		
  		}
  		else {
  			$count = parent::doCount($criteria, $distinct, $con);
			
  			if ($cache != null) {
	  			$cache->set($key,serialize($count)); 
	  		}
	  		
			return $count;
  		}
	}
} // PropuestaPeer
