<?php

require 'lib/model/om/BasePropuesta.php';


/**
 * Skeleton subclass for representing a row from the 'propuesta' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Fri Apr  9 16:18:01 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Propuesta extends BasePropuesta implements reviewable {
	const NUM_ENTITY = 3;

  public function __toString()
  {
    return $this->getLongName();
  }
  public function getLongName()
  {
  	return $this->getTitulo();
  }
  
  public function getPositives() {
  	return SfReviewManager::getTotalReviewsByEntityAndValue(Propuesta::NUM_ENTITY, $this->getId(), 1);
  }
  
  public function getNegatives(){
  	return SfReviewManager::getTotalReviewsByEntityAndValue(Propuesta::NUM_ENTITY, $this->getId(), -1);
  }
  
  	public function applyDefaultValues()
	{
		if ($this->sumu == null || $this->sumu == ''){
			$this->sumu = 0;
		}
		if ($this->sumd == null || $this->sumd == ''){
			$this->sumd = 0;
		}
	}
  
	var $sumut = 0;
	var $sumdt = 0;
	public function getSumut(){
		return $this->sumut;
	}
	public function setSumut($v){
		return $this->sumut = $v;
	}
	public function getSumdt(){
		return $this->sumdt;
	}
	public function setSumdt($v){
		return $this->sumdt = $v;
	}
	
	public function getTotalt(){
		return $this->sumut + $this->sumdt;
	}
	public function getPath(){
		return 'propuestas';
	}
	public function getModule(){
		return 'propuesta';
	}
	public function getImagen(){
		$img = parent::getImagen();
		return $img?$img:'p_unknown.png';
	}
	public function getImagePath(){
		return "propuestas";
	}
	
  public function getType()
  {
    return self::NUM_ENTITY;
  }
  public function updateCalcs(){
  	$this->setSumu($this->getPositives());
  	$this->setSumd($this->getNegatives());
  }

  public function getDescription()
  {
    return $this->getDescripcion();
  }
} // Propuesta
