generator:
  class: sfPropelGenerator
  param:
    model_class:           Eleccion
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          eleccion
    with_propel_route:     1

    config:
      actions: ~
      list:
        title:   Elecciones
        display: [id,vanity]

      filter:
        display: [vanity,created_at]
      form:    ~
      form:
        display:
          "Datos de las elecciones": [vanity]
          "Instituciones": []
          "Traducibles": [es,ca]

      edit:
        title:   Elecci&oacute;n
      new:
        title:   Nueva elecci&oacute;n
