# default values
all:
  sfImageTransformPlugin:
    default_adapter: GD # GD or ImageMagick
    default_image: { mime_type: image/png, filename: Untitled.png }
    font_dir: /usr/share/fonts/truetype/msttcorefonts
    mime_type:
      auto_detect: true
      library: gd_mime_type # Fileinfo (PECL), MIME_Type (PEAR)
  sf_guard_plugin:
    profile_class:      SfGuardUserProfile
    profile_field_name: user_id