# default values
all:
  facebook: 
    api_key: 401234585a2ddbd0a97c9c56e8008299
    api_secret: 0f841360f87ec4f2c12c659e41f5bd1c 
    api_id: xxx
    redirect_after_connect: false 
    redirect_after_connect_url: '' 
    connect_signin_url: 'sfFacebookConnectAuth/signin' 
    app_url: '/my-app' # the facebook application canvas url 
    guard_adapter: ~ # to customise a guard adapter 
    js_framework: jQuery
    
  sf_guard_plugin: 
    profile_class:      SfGuardUserProfile
    profile_field_name: user_id
    profile_facebook_uid_name: facebook_uid 
    profile_email_name: email 
    profile_email_hash_name: email_hash

  facebook_connect: 
    load_routing: true 
    user_permissions: []
    
  sfImageTransformPlugin:
    default_adapter: GD # GD or ImageMagick
    default_image: { mime_type: image/png, filename: Untitled.png }
    font_dir: /usr/share/fonts/truetype/msttcorefonts
    mime_type:
      auto_detect: true
      library: gd_mime_type # Fileinfo (PECL), MIME_Type (PEAR)
    
  enable_vobase_me: true