rendering: ~

facebook_connect:
  class: sfFacebookConnectFilter
remember_me:
  class: sfGuardRememberMeFilter
security:
  class: voSecurityFilter

redirect:
  class: voRedirectFilter
culture:
  class: voCultureFilter
vobase:
  class: voBaseFilter
browser:
  class: voBrowserFilter



cache:     ~
common:
  class: sfCommonFilter
execution: ~
