rendering: ~
security:
  class: voSecurityFilter

redirect:
  class: voRedirectFilter
culture:
  class: voCultureFilter
vobase:
  class: voBaseFilter

# insert your own filters here

cache:     ~
common:    ~
execution: ~
