rendering: ~

security:
  class: voSecurityFilter

redirect:
  class: voRedirectFilter
culture:
  class: voCultureFilter
vobase:
  class: voBaseFilter
browser:
  class: voBrowserFilter

# insert your own filters here

cache:     ~
common:
  class: sfCommonFilter
execution: ~
