# default rules

### API ###

api:
  url:   /a1
  param: { module: api, action: api }

### HOME ###

homepage:
  url:   /
  param: { module: home, action: index }

### PROPUESTAS ###

propuesta_edit_links:
  url: /propuesta/el/:id
  param: { module: propuesta, action: editEnlaces }
    
propuesta_edit_doc:
  url: /propuesta/ed/:id
  param: { module: propuesta, action: editDoc }    

ranking_propuesta_es:
  url: /propuestas
  param: { module: propuesta, action: ranking }
  class:  sfRequestHostCultureRoute
  requirements:
    sf_host_culture: es

ranking_propuesta_ca:
  url: /propostes
  param: { module: propuesta, action: ranking }
  class:  sfRequestHostCultureRoute
  requirements:
    sf_host_culture: cat
        
propuesta_add_es:
  url: /propuesta/add
  param: { module: propuesta, action: new }
  class:  sfRequestHostCultureRoute
  requirements:
    sf_host_culture: es
        
propuesta_add_ca:
  url: /proposta/add
  param: { module: propuesta, action: new }
  class:  sfRequestHostCultureRoute
  requirements:
        
propuesta_edit_es:
  url: /propuesta/edit/:id
  param: { module: propuesta, action: edit }
  class:  sfRequestHostCultureRoute
  requirements:
    sf_host_culture: es
        
propuesta_edit_ca:
  url: /proposta/edit/:id
  param: { module: propuesta, action: edit }
  class:  sfRequestHostCultureRoute
  requirements:
    sf_host_culture: cat  
        
propuesta_show_es:
  url: /propuesta/:id
  param: { module: propuesta, action: show }
  class:  sfRequestHostCultureRoute
  requirements:
    sf_host_culture: es
        
propuesta_show_ca:
  url: /proposta/:id
  param: { module: propuesta, action: show }
  class:  sfRequestHostCultureRoute
  requirements:
    sf_host_culture: cat
    
### POLITICOS ###
    
partido_ac_partido:
  url: /politico/ac_partido
  param: { module: politico, action: acPartido }
    
partido_ac_institucion:
  url: /politico/ac_institucion
  param: { module: politico, action: acInstitucion }
    
politico_more_comments:
  url: /politics/more
  param: { module: politico, action: moreComments }
  
politico_es:
  url: /politico/:id
  param: { module: politico, action: show }
  class:  sfRequestHostCultureRoute
  requirements:
    sf_host_culture: es

politico_ca:
  url: /politic/:id
  param: { module: politico, action: show }
  class:  sfRequestHostCultureRoute
  requirements:
    sf_host_culture: cat
    
ranking_es:
  url: /politicos/:partido/:institucion
  param: { module: politico, action: ranking }
  class:  sfRequestHostCultureRoute
  requirements:
    sf_host_culture: es
  
ranking_ca:
  url: /politics/:partido/:institucion
  param: { module: politico, action: ranking }
  class:  sfRequestHostCultureRoute
  requirements:
    sf_host_culture: cat
  
ranking_partido_es:
  url: /politicos/:partido
  param: { module: politico, action: ranking }
  class:  sfRequestHostCultureRoute
  requirements:
    sf_host_culture: es
  
ranking_partido_ca:
  url: /politics/:partido
  param: { module: politico, action: ranking }
  class:  sfRequestHostCultureRoute
  requirements:
    sf_host_culture: cat 
    
ranking_all_es:
  url: /politicos
  param: { module: politico, action: ranking }
  class:  sfRequestHostCultureRoute
  requirements:
    sf_host_culture: es
    
ranking_all_ca:
  url: /politics
  param: { module: politico, action: ranking }
  class:  sfRequestHostCultureRoute
  requirements:
    sf_host_culture: cat
  
politico_take:
  url:   /take
  param: { module: politico, action: take }
  
### PARTIDOS ###
    
partido_es:
  url: /partido/:id
  param: { module: partido, action: show }
  class:  sfRequestHostCultureRoute
  requirements:
    sf_host_culture: es
  
partido_ca:
  url: /partit/:id
  param: { module: partido, action: show }
  class:  sfRequestHostCultureRoute
  requirements:
    sf_host_culture: cat
  
partido_filter:
  url: /partidos/filter
  param: { module: partido, action: filter }

partido_more_comments:
  url: /partidos/more
  param: { module: partido, action: moreComments }
  
ranking_partidos_institucion_es:
  url: /partidos/:institucion
  param: { module: partido, action: ranking }
  class:  sfRequestHostCultureRoute
  requirements:
    sf_host_culture: es
  
ranking_partidos_institucion_ca:
  url: /partits/:institucion
  param: { module: partido, action: ranking }
  class:  sfRequestHostCultureRoute
  requirements:
    sf_host_culture: cat

ranking_partidos_es:
  url: /partidos
  param: { module: partido, action: ranking }
  class:  sfRequestHostCultureRoute
  requirements:
    sf_host_culture: es
  
ranking_partidos_ca:
  url: /partits
  param: { module: partido, action: ranking }
  class:  sfRequestHostCultureRoute
  requirements:
    sf_host_culture: cat

### USUARIOS ###

sf_guard_signin:
  url:   /user/login
  param: { module: sfGuardAuth, action: signin } 

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

usuario_confirm:
  url:   /user/confirm/:codigo
  param: { module: sfGuardAuth, action: confirm }
  

usuario_unsubscribe:
  url:   /user/unsubscribe/:codigo
  param: { module: sfGuardAuth, action: unsubscribe }
  

usuario_removeTip:
  url:   /user/removetip
  param: { module: sfGuardAuth, action: removeTip }  

usuario_votos:
  url:   /user/reviews
  param: { module: perfil, action: reviews }

profile_more_comments:
  url: /user/more
  param: { module: perfil, action: more }

usuario_edit:
  url: /user/edit
  param: { module: sfGuardAuth, action: edit }

usuario_fb_edit:
  url: /user/editFB
  param: { module: sfGuardAuth, action: editFB }
  
usuario_fb_confirm_merge:
  url: /user/confirmMerge
  param: { module: sfGuardAuth, action: confirmMerge }
  
usuario_remove_confirm:
  url: /user/remove/:codigo
  param: { module: sfGuardAuth, action: remove }
  
usuario_remove:
  url: /user/remove
  param: { module: sfGuardAuth, action: remove }
  
usuario_reminder:
  url: /user/reminder 
  param: { module: sfGuardAuth, action: reminder }

usuario_change_password:
  url:   /user/password/:codigo
  param: { module: sfGuardAuth, action: changePassword }

usuario_change_password2:
  url:   /user/password
  param: { module: sfGuardAuth, action: changePassword }
  
### REVIEWS ###
  
sf_review_form:
  url:   /review/form
  param: { module: sfReviewFront, action: form } 

sf_review_show:
  url:   /r/:id
  param: { module: sfReviewFront, action: show }

sf_review_preview:
  url:   /review/preview
  param: { module: sfReviewFront, action: preview }  

sf_review_send:
  url:   /review/send
  param: { module: sfReviewFront, action: send }  
  
sf_review_init:
  url:   /review/init
  param: { module: sfReviewFront, action: init } 
 
sf_review_delete:
  url:   /review/delete
  param: { module: sfReviewFront, action: delete } 
  
sf_review_list:
  url:   /review/list
  param: { module: sfReviewFront, action: list } 
  
sf_review_filtered_list:
  url:   /review/filteredList
  param: { module: sfReviewFront, action: filteredList }
  
sf_review_quickvote:
  url:   /review/qv
  param: { module: sfReviewFront, action: quickvote }

### GENERAL/OTROS ###  

about:
  url:   /about
  param: { module: general, action: about }
  
rules:
  url:   /dos-and-donts
  param: { module: general, action: rules }
  
search:
  url:   /search
  param: { module: general, action: search }
  
### PERFIL ###  

contact:
  url:   /contact
  param: { module: general, action: contact }
  
usuario_contact:
  url:   /:username/contact
  param: { module: perfil, action: contact }
  
usuario:
  url:   /:username
  param: { module: perfil, action: show }

### API DEMO ###  

api_demo_auth:
  url:   /api_demo/auth
  param: { module: api_demo, action: auth }

api_demo_callback:
  url:   /api_demo/callback
  param: { module: api_demo, action: callback }
  
api_demo_most_recently_voted:
  url:   /api_demo/most_recently_voted
  param: { module: api_demo, action: mostRecentlyVoted }
  
api_demo_politicos:
  url:   /api_demo/politicos
  param: { module: api_demo, action: politicos }
  
api_demo_put:
  url:   /api_demo/post
  param: { module: api_demo, action: postReview }
  
api_demo_reviews:
  url:   /api_demo/reviews
  param: { module: api_demo, action: reviews }
  
api_demo_search:
  url:   /api_demo/search
  param: { module: api_demo, action: search }
  
api_demo_search:
  url:   /api_demo/proposal/:id
  param: { module: api_demo, action: proposal }
        
### ELECCIONES ###
        
eleccion_show_es:
  url: /eleccion/:id
  param: { module: eleccion, action: show }
  class:  sfRequestHostCultureRoute
  requirements:
    sf_host_culture: es
    
eleccion_show_ca:
  url: /eleccion/:id
  param: { module: eleccion, action: show }
  class:  sfRequestHostCultureRoute
  requirements:
    sf_host_culture: cat