# default rules
api:
  url:   /a1
  param: { module: api, action: api }

homepage:
  url:   /:sf_culture
  param: { module: home, action: index }
  requirements: { sf_culture: (?:es|ca) }

sf_guard_signin:
  url:   /:sf_culture/user/login
  param: { module: sfGuardAuth, action: signin }
  requirements: { sf_culture: (?:es|ca) }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

usuario_removeTip:
  url:   /:sf_culture/user/removetip
  param: { module: sfGuardAuth, action: removeTip }
  requirements: { sf_culture: (?:es|ca) }

usuario_votos:
  url:   /:sf_culture/user/reviews
  param: { module: perfil, action: reviews }

usuario_edit:
  url: /:sf_culture/user/edit
  param: { module: sfGuardAuth, action: edit }

usuario_fb_edit:
  url: /:sf_culture/user/editFB
  param: { module: sfGuardAuth, action: editFB }
  
usuario_fb_confirm_merge:
  url: /:sf_culture/user/confirmMerge
  param: { module: sfGuardAuth, action: confirmMerge }

usuario_reminder:
  url: /:sf_culture/user/reminder 
  param: { module: sfGuardAuth, action: reminder }

about:
  url:   /:sf_culture/about
  param: { module: general, action: about }
  requirements: { sf_culture: (?:es|ca) }

search:
  url:   /:sf_culture/search
  param: { module: general, action: search }
  requirements: { sf_culture: (?:es|ca) }

contact:
  url:   /:sf_culture/contact
  param: { module: general, action: contact }
  requirements: { sf_culture: (?:es|ca) }

api_demo_auth:
  url:   /api_demo/auth
  param: { module: api_demo, action: auth }

api_demo_callback:
  url:   /api_demo/callback
  param: { module: api_demo, action: callback }
  
api_demo_most_recently_voted:
  url:   /api_demo/most_recently_voted
  param: { module: api_demo, action: mostRecentlyVoted }
  
api_demo_politicos:
  url:   /api_demo/politicos
  param: { module: api_demo, action: politicos }
api_demo_put:
  url:   /api_demo/post
  param: { module: api_demo, action: postReview }

