# default rules
homepage_redirect:
  url:   /
  param: { module: home, action: indexWithoutCulture }

homepage:
  url:   /:sf_culture
  param: { module: home, action: index }
  requirements: { sf_culture: (?:es|ca) }

politico_es:
  url: /:sf_culture/politico/:id
  param: { module: politico, action: show }
  requirements: { sf_culture: (?:es) }

politico_ca:
  url: /:sf_culture/politic/:id
  param: { module: politico, action: show }
  requirements: { sf_culture: (?:ca) }

ranking_es_all:
  url: /:sf_culture/politicos
  param: { module: politico, action: ranking }
  requirements: { sf_culture: (?:es) }

ranking_ca_all:
  url: /:sf_culture/politics
  param: { module: politico, action: ranking }
  requirements: { sf_culture: (?:ca) }

ranking_es_partido:
  url: /:sf_culture/politicos/:partido
  param: { module: politico, action: ranking }
  requirements: { sf_culture: (?:es) }

ranking_ca_partido:
  url: /:sf_culture/politics/:partido
  param: { module: politico, action: ranking }
  requirements: { sf_culture: (?:ca) }

ranking_es:
  url: /:sf_culture/politicos/:partido/:institucion
  param: { module: politico, action: ranking }
  requirements: { sf_culture: (?:es) }

ranking_ca:
  url: /:sf_culture/politicos/:partido/:institucion
  param: { module: politico, action: ranking }
  requirements: { sf_culture: (?:ca) }

partido_es:
  url: /:sf_culture/partido/:id
  param: { module: partido, action: show }
  requirements: { sf_culture: (?:es) }

partido_ca:
  url: /:sf_culture/partit/:id
  param: { module: partido, action: show }
  requirements: { sf_culture: (?:ca) }

sf_guard_signin:
  url:   /:sf_culture/user/login
  param: { module: sfGuardAuth, action: signin }
  requirements: { sf_culture: (?:es|ca) }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

usuario_confirm:
  url:   /:sf_culture/user/confirm/:codigo
  param: { module: sfGuardAuth, action: confirm }
  requirements: { sf_culture: (?:es|ca) }

usuario:
  url:   /:username
  param: { module: sfGuardAuth, action: show }

usuario_edit:
  url: /:sf_culture/user/edit
  param: { module: sfGuardAuth, action: edit }
  
usuario_reminder:
  url: /:sf_culture/user/reminder 
  param: { module: sfGuardAuth, action: reminder }
  
usuario_reminder_sent: 
  url: /:sf_culture/user/reminder-sent
  param: { module: sfGuardAuth, action: reminderSent }

sf_review_form:
  url:   /review/form
  param: { module: sfReviewFront, action: form }

sf_review_preview:
  url:   /review/preview
  param: { module: sfReviewFront, action: preview }

sf_review_send:
  url:   /review/send
  param: { module: sfReviewFront, action: send }


# default_index:
#   url:   /:module
#   param: { action: index }

#default_culture:
#  url:   /:sf_culture/:module/:action/*
#  requirements: { sf_culture: (?:es|ca) }

# default:
#   url:   /:module/:action/*
