default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [ui-lightness/jquery-ui-1.7.2.custom.css, /sfReviewPlugin/css/sf_review.css?'. sfConfig::get('sf_ml') .', screen.css?'. sfConfig::get('sf_ml') .']

  javascripts: [flot/jquery.flot.js, /sfReviewPlugin/js/sf_review.js?'. sfConfig::get('sf_ml') .', /sfReviewPlugin/js/jquery.hint.js, voota.js?'. sfConfig::get('sf_ml') .', /sfJqueryReloadedPlugin/js/jquery-ui-1.7.2.custom.min.js]

  has_layout:     true
  layout:         layout
