default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [ui-voota/jquery-ui-1.8.custom.css, /sfReviewPlugin/css/sf_review.css?'. sfConfig::get('sf_ml') .', screen.css?'. sfConfig::get('sf_ml') .']

  javascripts: [http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js, http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js, voota.js?'. sfConfig::get('sf_ml') .', ajaxupload.js, /sfReviewPlugin/js/sf_review.js?'. sfConfig::get('sf_ml') .', /sfReviewPlugin/js/jquery.hint.js, jquery.qtip-1.0.0-rc3.min.js, bluff/js-class.js, bluff/excanvas.js, bluff/bluff.js, bluff/custom.js]

  has_layout:     true
  layout:         layout
