generator:
  class: sfPropelGenerator
  param:
    model_class:           Usuario
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          usuario
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:
        display: 
          "Datos voota": [email,clave,acepta_mensajes,formacion,presentacion]
          "Datos personales": [nombre,apellidos,fecha_nacimiento,pais,residencia]
      edit:
        title:   Usuario
      new:
        title:   Nuevo usuario


      list:
        title:   Usuarios
        display: [id,email,nombre,apellidos]

