<?php

/**
 * Base class that represents a row from the 'geo' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Sun Oct 10 23:35:36 2010
 *
 * @package    lib.model.om
 */
abstract class BaseGeo extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        GeoPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the nombre field.
	 * @var        string
	 */
	protected $nombre;

	/**
	 * The value for the geo_id field.
	 * @var        int
	 */
	protected $geo_id;

	/**
	 * The value for the codigo field.
	 * @var        int
	 */
	protected $codigo;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * @var        Geo
	 */
	protected $aGeoRelatedByGeoId;

	/**
	 * @var        array Geo[] Collection to store aggregation of Geo objects.
	 */
	protected $collGeosRelatedByGeoId;

	/**
	 * @var        Criteria The criteria used to select the current contents of collGeosRelatedByGeoId.
	 */
	private $lastGeoRelatedByGeoIdCriteria = null;

	/**
	 * @var        array Institucion[] Collection to store aggregation of Institucion objects.
	 */
	protected $collInstitucions;

	/**
	 * @var        Criteria The criteria used to select the current contents of collInstitucions.
	 */
	private $lastInstitucionCriteria = null;

	/**
	 * @var        array Circunscripcion[] Collection to store aggregation of Circunscripcion objects.
	 */
	protected $collCircunscripcions;

	/**
	 * @var        Criteria The criteria used to select the current contents of collCircunscripcions.
	 */
	private $lastCircunscripcionCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'GeoPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [nombre] column value.
	 * 
	 * @return     string
	 */
	public function getNombre()
	{
		return $this->nombre;
	}

	/**
	 * Get the [geo_id] column value.
	 * 
	 * @return     int
	 */
	public function getGeoId()
	{
		return $this->geo_id;
	}

	/**
	 * Get the [codigo] column value.
	 * 
	 * @return     int
	 */
	public function getCodigo()
	{
		return $this->codigo;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Geo The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = GeoPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [nombre] column.
	 * 
	 * @param      string $v new value
	 * @return     Geo The current object (for fluent API support)
	 */
	public function setNombre($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->nombre !== $v) {
			$this->nombre = $v;
			$this->modifiedColumns[] = GeoPeer::NOMBRE;
		}

		return $this;
	} // setNombre()

	/**
	 * Set the value of [geo_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Geo The current object (for fluent API support)
	 */
	public function setGeoId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->geo_id !== $v) {
			$this->geo_id = $v;
			$this->modifiedColumns[] = GeoPeer::GEO_ID;
		}

		if ($this->aGeoRelatedByGeoId !== null && $this->aGeoRelatedByGeoId->getId() !== $v) {
			$this->aGeoRelatedByGeoId = null;
		}

		return $this;
	} // setGeoId()

	/**
	 * Set the value of [codigo] column.
	 * 
	 * @param      int $v new value
	 * @return     Geo The current object (for fluent API support)
	 */
	public function setCodigo($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->codigo !== $v) {
			$this->codigo = $v;
			$this->modifiedColumns[] = GeoPeer::CODIGO;
		}

		return $this;
	} // setCodigo()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Geo The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = GeoPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->nombre = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->geo_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->codigo = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->created_at = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 5; // 5 = GeoPeer::NUM_COLUMNS - GeoPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Geo object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aGeoRelatedByGeoId !== null && $this->geo_id !== $this->aGeoRelatedByGeoId->getId()) {
			$this->aGeoRelatedByGeoId = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(GeoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = GeoPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aGeoRelatedByGeoId = null;
			$this->collGeosRelatedByGeoId = null;
			$this->lastGeoRelatedByGeoIdCriteria = null;

			$this->collInstitucions = null;
			$this->lastInstitucionCriteria = null;

			$this->collCircunscripcions = null;
			$this->lastCircunscripcionCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(GeoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseGeo:delete:pre') as $callable)
			{
			  if ($ret = call_user_func($callable, $this, $con))
			  {
			    return;
			  }
			}

			if ($ret) {
				GeoPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseGeo:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(GeoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseGeo:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			
			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(GeoPeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseGeo:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				GeoPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aGeoRelatedByGeoId !== null) {
				if ($this->aGeoRelatedByGeoId->isModified() || $this->aGeoRelatedByGeoId->isNew()) {
					$affectedRows += $this->aGeoRelatedByGeoId->save($con);
				}
				$this->setGeoRelatedByGeoId($this->aGeoRelatedByGeoId);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = GeoPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = GeoPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += GeoPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collGeosRelatedByGeoId !== null) {
				foreach ($this->collGeosRelatedByGeoId as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collInstitucions !== null) {
				foreach ($this->collInstitucions as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collCircunscripcions !== null) {
				foreach ($this->collCircunscripcions as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aGeoRelatedByGeoId !== null) {
				if (!$this->aGeoRelatedByGeoId->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aGeoRelatedByGeoId->getValidationFailures());
				}
			}


			if (($retval = GeoPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collGeosRelatedByGeoId !== null) {
					foreach ($this->collGeosRelatedByGeoId as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collInstitucions !== null) {
					foreach ($this->collInstitucions as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collCircunscripcions !== null) {
					foreach ($this->collCircunscripcions as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = GeoPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getNombre();
				break;
			case 2:
				return $this->getGeoId();
				break;
			case 3:
				return $this->getCodigo();
				break;
			case 4:
				return $this->getCreatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = GeoPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getNombre(),
			$keys[2] => $this->getGeoId(),
			$keys[3] => $this->getCodigo(),
			$keys[4] => $this->getCreatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = GeoPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setNombre($value);
				break;
			case 2:
				$this->setGeoId($value);
				break;
			case 3:
				$this->setCodigo($value);
				break;
			case 4:
				$this->setCreatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = GeoPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setNombre($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setGeoId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setCodigo($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setCreatedAt($arr[$keys[4]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(GeoPeer::DATABASE_NAME);

		if ($this->isColumnModified(GeoPeer::ID)) $criteria->add(GeoPeer::ID, $this->id);
		if ($this->isColumnModified(GeoPeer::NOMBRE)) $criteria->add(GeoPeer::NOMBRE, $this->nombre);
		if ($this->isColumnModified(GeoPeer::GEO_ID)) $criteria->add(GeoPeer::GEO_ID, $this->geo_id);
		if ($this->isColumnModified(GeoPeer::CODIGO)) $criteria->add(GeoPeer::CODIGO, $this->codigo);
		if ($this->isColumnModified(GeoPeer::CREATED_AT)) $criteria->add(GeoPeer::CREATED_AT, $this->created_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(GeoPeer::DATABASE_NAME);

		$criteria->add(GeoPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Geo (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setNombre($this->nombre);

		$copyObj->setGeoId($this->geo_id);

		$copyObj->setCodigo($this->codigo);

		$copyObj->setCreatedAt($this->created_at);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getGeosRelatedByGeoId() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addGeoRelatedByGeoId($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getInstitucions() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addInstitucion($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getCircunscripcions() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addCircunscripcion($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Geo Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     GeoPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new GeoPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Geo object.
	 *
	 * @param      Geo $v
	 * @return     Geo The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setGeoRelatedByGeoId(Geo $v = null)
	{
		if ($v === null) {
			$this->setGeoId(NULL);
		} else {
			$this->setGeoId($v->getId());
		}

		$this->aGeoRelatedByGeoId = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Geo object, it will not be re-added.
		if ($v !== null) {
			$v->addGeoRelatedByGeoId($this);
		}

		return $this;
	}


	/**
	 * Get the associated Geo object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Geo The associated Geo object.
	 * @throws     PropelException
	 */
	public function getGeoRelatedByGeoId(PropelPDO $con = null)
	{
		if ($this->aGeoRelatedByGeoId === null && ($this->geo_id !== null)) {
			$this->aGeoRelatedByGeoId = GeoPeer::retrieveByPk($this->geo_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aGeoRelatedByGeoId->addGeosRelatedByGeoId($this);
			 */
		}
		return $this->aGeoRelatedByGeoId;
	}

	/**
	 * Clears out the collGeosRelatedByGeoId collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addGeosRelatedByGeoId()
	 */
	public function clearGeosRelatedByGeoId()
	{
		$this->collGeosRelatedByGeoId = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collGeosRelatedByGeoId collection (array).
	 *
	 * By default this just sets the collGeosRelatedByGeoId collection to an empty array (like clearcollGeosRelatedByGeoId());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initGeosRelatedByGeoId()
	{
		$this->collGeosRelatedByGeoId = array();
	}

	/**
	 * Gets an array of Geo objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Geo has previously been saved, it will retrieve
	 * related GeosRelatedByGeoId from storage. If this Geo is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Geo[]
	 * @throws     PropelException
	 */
	public function getGeosRelatedByGeoId($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(GeoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collGeosRelatedByGeoId === null) {
			if ($this->isNew()) {
			   $this->collGeosRelatedByGeoId = array();
			} else {

				$criteria->add(GeoPeer::GEO_ID, $this->id);

				GeoPeer::addSelectColumns($criteria);
				$this->collGeosRelatedByGeoId = GeoPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(GeoPeer::GEO_ID, $this->id);

				GeoPeer::addSelectColumns($criteria);
				if (!isset($this->lastGeoRelatedByGeoIdCriteria) || !$this->lastGeoRelatedByGeoIdCriteria->equals($criteria)) {
					$this->collGeosRelatedByGeoId = GeoPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastGeoRelatedByGeoIdCriteria = $criteria;
		return $this->collGeosRelatedByGeoId;
	}

	/**
	 * Returns the number of related Geo objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Geo objects.
	 * @throws     PropelException
	 */
	public function countGeosRelatedByGeoId(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(GeoPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collGeosRelatedByGeoId === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(GeoPeer::GEO_ID, $this->id);

				$count = GeoPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(GeoPeer::GEO_ID, $this->id);

				if (!isset($this->lastGeoRelatedByGeoIdCriteria) || !$this->lastGeoRelatedByGeoIdCriteria->equals($criteria)) {
					$count = GeoPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collGeosRelatedByGeoId);
				}
			} else {
				$count = count($this->collGeosRelatedByGeoId);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Geo object to this object
	 * through the Geo foreign key attribute.
	 *
	 * @param      Geo $l Geo
	 * @return     void
	 * @throws     PropelException
	 */
	public function addGeoRelatedByGeoId(Geo $l)
	{
		if ($this->collGeosRelatedByGeoId === null) {
			$this->initGeosRelatedByGeoId();
		}
		if (!in_array($l, $this->collGeosRelatedByGeoId, true)) { // only add it if the **same** object is not already associated
			array_push($this->collGeosRelatedByGeoId, $l);
			$l->setGeoRelatedByGeoId($this);
		}
	}

	/**
	 * Clears out the collInstitucions collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addInstitucions()
	 */
	public function clearInstitucions()
	{
		$this->collInstitucions = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collInstitucions collection (array).
	 *
	 * By default this just sets the collInstitucions collection to an empty array (like clearcollInstitucions());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initInstitucions()
	{
		$this->collInstitucions = array();
	}

	/**
	 * Gets an array of Institucion objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Geo has previously been saved, it will retrieve
	 * related Institucions from storage. If this Geo is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Institucion[]
	 * @throws     PropelException
	 */
	public function getInstitucions($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(GeoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collInstitucions === null) {
			if ($this->isNew()) {
			   $this->collInstitucions = array();
			} else {

				$criteria->add(InstitucionPeer::GEO_ID, $this->id);

				InstitucionPeer::addSelectColumns($criteria);
				$this->collInstitucions = InstitucionPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(InstitucionPeer::GEO_ID, $this->id);

				InstitucionPeer::addSelectColumns($criteria);
				if (!isset($this->lastInstitucionCriteria) || !$this->lastInstitucionCriteria->equals($criteria)) {
					$this->collInstitucions = InstitucionPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastInstitucionCriteria = $criteria;
		return $this->collInstitucions;
	}

	/**
	 * Returns the number of related Institucion objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Institucion objects.
	 * @throws     PropelException
	 */
	public function countInstitucions(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(GeoPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collInstitucions === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(InstitucionPeer::GEO_ID, $this->id);

				$count = InstitucionPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(InstitucionPeer::GEO_ID, $this->id);

				if (!isset($this->lastInstitucionCriteria) || !$this->lastInstitucionCriteria->equals($criteria)) {
					$count = InstitucionPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collInstitucions);
				}
			} else {
				$count = count($this->collInstitucions);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Institucion object to this object
	 * through the Institucion foreign key attribute.
	 *
	 * @param      Institucion $l Institucion
	 * @return     void
	 * @throws     PropelException
	 */
	public function addInstitucion(Institucion $l)
	{
		if ($this->collInstitucions === null) {
			$this->initInstitucions();
		}
		if (!in_array($l, $this->collInstitucions, true)) { // only add it if the **same** object is not already associated
			array_push($this->collInstitucions, $l);
			$l->setGeo($this);
		}
	}

	/**
	 * Clears out the collCircunscripcions collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addCircunscripcions()
	 */
	public function clearCircunscripcions()
	{
		$this->collCircunscripcions = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collCircunscripcions collection (array).
	 *
	 * By default this just sets the collCircunscripcions collection to an empty array (like clearcollCircunscripcions());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initCircunscripcions()
	{
		$this->collCircunscripcions = array();
	}

	/**
	 * Gets an array of Circunscripcion objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Geo has previously been saved, it will retrieve
	 * related Circunscripcions from storage. If this Geo is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Circunscripcion[]
	 * @throws     PropelException
	 */
	public function getCircunscripcions($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(GeoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCircunscripcions === null) {
			if ($this->isNew()) {
			   $this->collCircunscripcions = array();
			} else {

				$criteria->add(CircunscripcionPeer::GEO_ID, $this->id);

				CircunscripcionPeer::addSelectColumns($criteria);
				$this->collCircunscripcions = CircunscripcionPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(CircunscripcionPeer::GEO_ID, $this->id);

				CircunscripcionPeer::addSelectColumns($criteria);
				if (!isset($this->lastCircunscripcionCriteria) || !$this->lastCircunscripcionCriteria->equals($criteria)) {
					$this->collCircunscripcions = CircunscripcionPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastCircunscripcionCriteria = $criteria;
		return $this->collCircunscripcions;
	}

	/**
	 * Returns the number of related Circunscripcion objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Circunscripcion objects.
	 * @throws     PropelException
	 */
	public function countCircunscripcions(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(GeoPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collCircunscripcions === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(CircunscripcionPeer::GEO_ID, $this->id);

				$count = CircunscripcionPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(CircunscripcionPeer::GEO_ID, $this->id);

				if (!isset($this->lastCircunscripcionCriteria) || !$this->lastCircunscripcionCriteria->equals($criteria)) {
					$count = CircunscripcionPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collCircunscripcions);
				}
			} else {
				$count = count($this->collCircunscripcions);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Circunscripcion object to this object
	 * through the Circunscripcion foreign key attribute.
	 *
	 * @param      Circunscripcion $l Circunscripcion
	 * @return     void
	 * @throws     PropelException
	 */
	public function addCircunscripcion(Circunscripcion $l)
	{
		if ($this->collCircunscripcions === null) {
			$this->initCircunscripcions();
		}
		if (!in_array($l, $this->collCircunscripcions, true)) { // only add it if the **same** object is not already associated
			array_push($this->collCircunscripcions, $l);
			$l->setGeo($this);
		}
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collGeosRelatedByGeoId) {
				foreach ((array) $this->collGeosRelatedByGeoId as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collInstitucions) {
				foreach ((array) $this->collInstitucions as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collCircunscripcions) {
				foreach ((array) $this->collCircunscripcions as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collGeosRelatedByGeoId = null;
		$this->collInstitucions = null;
		$this->collCircunscripcions = null;
			$this->aGeoRelatedByGeoId = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseGeo:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseGeo::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseGeo
