<?php

/**
 * PluginSfReviewTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSfReviewTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSfReviewTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSfReviewType');
    }
}