generator:
  class: sfPropelGenerator
  param:
    model_class:           Institucion
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          institucion
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:    
        display: [nombre_corto,nombre,geo,disabled,orden]
        sort: [orden, asc]
      filter: 
        display: [geo_id, disabled,orden, nombre]
      form:    
        display: 
          "Datos generales": [geo_id,disabled,orden,url, imagen]
          "Traducibles": [es,ca]
      edit:    ~
      new:     ~
