politico_institucion:
  class: sfPropelRouteCollection
  options:
    model:                PoliticoInstitucion
    module:               politicoInstitucion
    prefix_path:          /politicoInstitucion
    column:               politico_id
    with_wildcard_routes: true

enlace:
  class: sfPropelRouteCollection
  options:
    model:                Enlace
    module:               enlace
    prefix_path:          enlace
    column:               id
    with_wildcard_routes: true

sf_review_status:
  class: sfPropelRouteCollection
  options:
    model:                SfReviewStatus
    module:               sfReviewStatus
    prefix_path:          sfReviewStatus
    column:               id
    with_wildcard_routes: true

sf_review:
  class: sfPropelRouteCollection
  options:
    model:                SfReview
    module:               sfReview
    prefix_path:          sfReview
    column:               id
    with_wildcard_routes: true

sf_review_type:
  class: sfPropelRouteCollection
  options:
    model:                SfReviewType
    module:               sfReviewType
    prefix_path:          sfReviewType
    column:               id
    with_wildcard_routes: true

geo:
  class: sfPropelRouteCollection
  options:
    model:                Geo
    module:               geo
    prefix_path:          geo
    column:               id
    with_wildcard_routes: true

politico_lista:
  class: sfPropelRouteCollection
  options:
    model:                PoliticoLista
    module:               politico_lista
    prefix_path:          politico_lista
    column:               id
    with_wildcard_routes: true

institucion:
  class: sfPropelRouteCollection
  options:
    model:                Institucion
    module:               institucion
    prefix_path:          institucion
    column:               id
    with_wildcard_routes: true

lista:
  class: sfPropelRouteCollection
  options:
    model:                Lista
    module:               lista
    prefix_path:          lista
    column:               id
    with_wildcard_routes: true

eleccion:
  class: sfPropelRouteCollection
  options:
    model:                Eleccion
    module:               eleccion
    prefix_path:          eleccion
    column:               id
    with_wildcard_routes: true

partido:
  class: sfPropelRouteCollection
  options:
    model:                Partido
    module:               partido
    prefix_path:          partido
    column:               id
    with_wildcard_routes: true

politico:
  class: sfPropelRouteCollection
  options:
    model:                Politico
    module:               politico
    prefix_path:          politico
    column:               id
    with_wildcard_routes: true

# default rules
homepage:
  url:   /
  param: { module: home, action: index }

default_index:
  url:   /:module
  param: { action: index }

 
default:
  url:   /:module/:action/*
