default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    []
  javascripts: [/sfJqueryReloadedPlugin/js/jquery-ui-1.7.2.custom.min.js]

  has_layout:     true
  layout:         layout
