default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    []
  javascripts: [/sfReviewPlugin/js/sf_review.js?'. sfConfig::get('sf_ml') .', voota.js?'. sfConfig::get('sf_ml') .', /sfJqueryReloadedPlugin/js/jquery-1.3.2.min.js, /sfJqueryReloadedPlugin/js/jquery-ui-1.7.2.custom.min.js]

  has_layout:     true
  layout:         layout
