<?php

require 'plugins/sfReviewPlugin/lib/model/om/BaseSfReview.php';


/**
 * Skeleton subclass for representing a row from the 'sf_review' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Wed May 12 12:54:53 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.sfReviewPlugin.lib.model
 */
class SfReview extends BaseSfReview {

	/**
	 * Initializes internal state of SfReview object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}

} // SfReview
