default:
  components:
    sparkline:  [partido, sparkline]
    sparkline_politico:  [politico, sparkline]
    subreviews:  [sfReviewFront, subreviews]
    
all:
  javascripts: [jquery.sparkline.min.js]
    