default:
  components:
    sparkline:  [general, sparkline]
    subreviews:  [sfReviewFront, subreviews]
    review_list:  [sfReviewFront, reviewList]
    quickvote:  [sfReviewFront, quickvote]
    tags:  [general, tags]
    tagList:  [general, tagList]
    
all:
  javascripts: 

filterSuccess:
  has_layout: false