default:
  components:
    sparkline:  [general, sparkline]
    subreviews:  [sfReviewFront, subreviews]
    review_list:  [sfReviewFront, reviewList]
    
all:
  javascripts: [jquery.sparkline.min.js]

filterSuccess:
  has_layout: false