propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native
  eleccion:
    _attributes: { phpName: Eleccion }
    id: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    nombre: { type: VARCHAR, size: '150', required: true }
    fecha: { type: DATE, required: false }
    created_at: { type: TIMESTAMP, required: false }
  eleccion_institucion:
    _attributes: { phpName: EleccionInstitucion }
    eleccion_id: { type: INTEGER, size: '11', primaryKey: true, required: true, foreignTable: eleccion, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    institucion_id: { type: INTEGER, size: '11', primaryKey: true, required: true, foreignTable: institucion, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    created_at: { type: TIMESTAMP, required: false }
    _indexes: { fk_ele_inst_eleccion: [eleccion_id], fk_ele_inst_institucion: [institucion_id] }
  enlace:
    _attributes: { phpName: Enlace }
    id: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    url: { type: VARCHAR, size: '150', required: true }
    tipo: { type: INTEGER, size: '11', required: false }
    partido_id: { type: INTEGER, size: '11', required: false, foreignTable: partido, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    politico_id: { type: INTEGER, size: '11', required: false, foreignTable: politico, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    sf_guard_user_id: { type: INTEGER, size: '11', required: false, foreignTable: sf_guard_user, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    orden: { type: INTEGER, size: '11', required: false }
    mostrar: { type: CHAR, size: '1', required: false }
    created_at: { type: TIMESTAMP, required: false }
    culture: { type: VARCHAR, size: '7', required: false }
    _indexes: { fk_e_partido: [partido_id], fk_e_politico: [politico_id] }
  geo:
    _attributes: { phpName: Geo }
    id: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    nombre: { type: VARCHAR, size: '150', required: true }
    created_at: { type: TIMESTAMP, required: false }
  imagen:
    _attributes: { phpName: Imagen }
    id: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    tipo: { type: CHAR, size: '1', required: false }
    partido_id: { type: INTEGER, size: '11', required: false, foreignTable: partido, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    politico_id: { type: INTEGER, size: '11', required: false, foreignTable: politico, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    opinion_id: { type: INTEGER, size: '11', required: false }
    created_at: { type: TIMESTAMP, required: false }
    _indexes: { fk_i_partido: [partido_id], fk_i_politico: [politico_id] }
  institucion:
    _attributes: { phpName: Institucion, isI18N: true, i18nTable: institucion_i18n }
    id: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    geo_id: { type: INTEGER, size: '11', required: false, foreignTable: geo, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    created_at: { type: TIMESTAMP, required: false }
    disabled: { type: CHAR, size: '1', required: false }
    orden: { type: INTEGER, size: '11', required: false }
    url: { type: VARCHAR, size: '255', required: false }
    imagen: { type: VARCHAR, size: '50', required: false }
    _indexes: { fk_geo: [geo_id] }
  institucion_i18n:
    _attributes: { phpName: InstitucionI18n }
    id: { type: INTEGER, size: '11', primaryKey: true, required: true, foreignTable: institucion, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    culture: { isCulture: true, type: VARCHAR, size: '7', primaryKey: true, required: true }
    vanity: { type: VARCHAR, size: '45', required: false }
    nombre_corto: { type: VARCHAR, size: '45', required: false }
    nombre: { type: VARCHAR, size: '150', required: true }
    _indexes: { fk_institucion_i18n_1: [id] }
    _uniques: { uniq_inst_i18n: [vanity,culture] }
  lista:
    _attributes: { phpName: Lista }
    id: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    partido_id: { type: INTEGER, size: '11', required: true, foreignTable: partido, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    eleccion_id: { type: INTEGER, size: '11', required: true, foreignTable: eleccion, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    created_at: { type: TIMESTAMP, required: false }
    _indexes: { fk_l_partido: [partido_id], fk_l_eleccion: [eleccion_id] }
  media:
    _attributes: { phpName: Media }
    idmedia: { type: INTEGER, size: '11', primaryKey: true, required: true }
    tipo: { type: CHAR, size: '1', required: false }
    idpolitico: { type: INTEGER, size: '11', required: false }
    idpartido: { type: INTEGER, size: '11', required: false }
  partido:
    _attributes: { phpName: Partido, isI18N: true, i18nTable: partido_i18n }
    id: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    abreviatura: { type: VARCHAR, size: '8', required: false }
    color: { type: VARCHAR, size: '8', required: false }
    created_at: { type: TIMESTAMP, required: false }
    partido_id: { type: INTEGER, size: '11', required: false, foreignTable: partido, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    imagen: { type: VARCHAR, size: '50', required: false }
    sumu: { type: INTEGER, size: '11', required: true, defaultValue: '0' }
    sumd: { type: INTEGER, size: '11', required: true, defaultValue: '0' }
    is_active: { type: boolean, required: true, default: 1 }
    is_main: { type: boolean, required: true, default: 1 }
    _indexes: { fk_partido_partido: [partido_id] }
    _uniques: { uniq_abreviatura: [abreviatura] }
  partido_i18n:
    _attributes: { phpName: PartidoI18n }
    id: { type: INTEGER, size: '11', primaryKey: true, required: true, foreignTable: partido, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    culture: { isCulture: true, type: VARCHAR, size: '7', primaryKey: true, required: true }
    nombre: { type: VARCHAR, size: '150', required: true }
    presentacion: { type: VARCHAR, size: '500', required: true }
    _indexes: { fk_partido_i18n_1: [id] }
  partido_lista:
    _attributes: { phpName: PartidoLista }
    partido_id: { type: INTEGER, size: '11', primaryKey: true, required: true, foreignTable: partido, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    lista_id: { type: INTEGER, size: '11', primaryKey: true, required: true, foreignTable: lista, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    created_at: { type: TIMESTAMP, required: false }
    _indexes: { fk_partido: [partido_id], fk_lista: [lista_id], fk_pl_partido: [partido_id], fk_pl_lista: [lista_id] }
  politico:
    _attributes: { phpName: Politico, isI18N: true, i18nTable: politico_i18n }
    id: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    alias: { type: VARCHAR, size: '45', required: false }
    nombre: { type: VARCHAR, size: '45', required: true }
    apellidos: { type: VARCHAR, size: '150', required: true }
    email: { type: VARCHAR, size: '45', required: false }
    sexo: { type: CHAR, size: '1', required: false }
    fecha_nacimiento: { type: DATE, required: false }
    pais: { type: VARCHAR, size: '45', required: false }
    residencia: { type: VARCHAR, size: '45', required: false }
    sf_guard_user_profile_id: { type: INTEGER, size: '11', required: false, foreignTable: sf_guard_user_profile, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    created_at: { type: TIMESTAMP, required: false }
    partido_id: { type: INTEGER, size: '11', required: false, foreignTable: partido, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    partido_txt: { type: VARCHAR, size: '150', required: false }
    imagen: { type: VARCHAR, size: '50', required: false }
    vanity: { type: VARCHAR, size: '45', required: false }
    lugar_nacimiento: { type: VARCHAR, size: '150', required: false }
    sumu: { type: INTEGER, size: '11', required: true, defaultValue: '0' }
    sumd: { type: INTEGER, size: '11', required: true, defaultValue: '0' }
    relacion: { type: CHAR, size: '2', required: false }
    hijos: { type: INTEGER, size: '11', required: false }
    hijas: { type: INTEGER, size: '11', required: false }
    _indexes: { fk_usuario: [sf_guard_user_profile_id], fk_politico_partido: [partido_id] }
    _uniques: { uniq_politico_vanity: [vanity] }
  politico_i18n:
    _attributes: { phpName: PoliticoI18n }
    id: { type: INTEGER, size: '11', primaryKey: true, required: true, foreignTable: politico, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    culture: { isCulture: true, type: VARCHAR, size: '7', primaryKey: true, required: true }
    formacion: { type: VARCHAR, size: '255', required: false }
    presentacion: { type: VARCHAR, size: '500', required: false }
    bio: { type: CLOB, required: false }
    _indexes: { fk_politico_i18n_1: [id] }
  politico_institucion:
    _attributes: { phpName: PoliticoInstitucion }
    politico_id: { type: INTEGER, size: '11', primaryKey: true, required: true, foreignTable: politico, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    institucion_id: { type: INTEGER, size: '11', primaryKey: true, required: true, foreignTable: institucion, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    fecha_inicio: { type: DATE, required: false }
    fecha_fin: { type: DATE, required: false }
    _indexes: { fk_institucion_politico_1: [institucion_id], fk_institucion_politico_2: [politico_id] }
  politico_lista:
    _attributes: { phpName: PoliticoLista }
    politico_id: { type: INTEGER, size: '11', primaryKey: true, required: true, foreignTable: politico, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    lista_id: { type: INTEGER, size: '11', primaryKey: true, required: true, foreignTable: lista, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    orden: { type: INTEGER, size: '11', required: false }
    created_at: { type: TIMESTAMP, required: false }
    _indexes: { fk_politico: [politico_id], fk_politico_lista_lista: [lista_id] }
  politico_temp:
    _attributes: { phpName: PoliticoTemp }
    email: { type: VARCHAR, size: '50', required: false }
    partido: { type: VARCHAR, size: '50', required: false }
    nombre: { type: VARCHAR, size: '50', required: false }
    apellidos: { type: VARCHAR, size: '100', required: false }
    bio: { type: CLOB, required: false }
  promocion:
    _attributes: { phpName: Promocion }
    id: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    fecha_inicio: { type: DATE, required: true }
    fecha_fin: { type: DATE, required: true }
    partido_id: { type: INTEGER, size: '11', required: false, foreignTable: partido, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    politico_id: { type: INTEGER, size: '11', required: false, foreignTable: politico, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    created_at: { type: TIMESTAMP, required: false }
    _indexes: { fk_pr_partido: [partido_id], fk_pr_politico: [politico_id] }
    
  sf_guard_user_profile:
    _attributes: { phpName: SfGuardUserProfile }
    id: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    user_id: { type: INTEGER, size: '11', required: true, foreignTable: sf_guard_user, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    nombre: { type: VARCHAR, size: '45', required: true }
    apellidos: { type: VARCHAR, size: '150', required: false }
    fecha_nacimiento: { type: DATE, required: false }
    pais: { type: VARCHAR, size: '45', required: false }
    formacion: { type: VARCHAR, size: '255', required: false }
    residencia: { type: VARCHAR, size: '45', required: false }
    presentacion: { type: VARCHAR, size: '500', required: false }
    created_at: { type: TIMESTAMP, required: false }
    vanity: { type: VARCHAR, size: '45', required: false }
    imagen: { type: VARCHAR, size: '50', required: false }
    codigo: { type: VARCHAR, size: '45', required: false }
    papel_voota: { type: VARCHAR, size: '280', required: false }
    mails_comentarios: { type: INTEGER, size: '11', required: true, defaultValue: '1' }
    mails_noticias: { type: INTEGER, size: '11', required: true, defaultValue: '1' }
    mails_contacto: { type: INTEGER, size: '11', required: true, defaultValue: '1' }
    mails_seguidor: { type: INTEGER, size: '11', required: true, defaultValue: '1' }
    numero_socio: { type: VARCHAR, size: '45', required: false }
    facebook_uid: { type: VARCHAR, size: '128', required: false, defaultValue: '1' }
    email: { type: VARCHAR, size: '255', required: false }
    email_hash: { type: VARCHAR, size: '255', required: false }
    _indexes: { fk_sf_guard_user_profile_user: [user_id] }
    _uniques: { uniq_sf_guard_user_profile_vanity: [vanity] }
