SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `voota`.`sf_review` ADD COLUMN `is_active` TINYINT(4) NOT NULL DEFAULT 1  AFTER `balance` ;

ALTER TABLE `voota`.`sf_review_type_entity` DROP FOREIGN KEY `fk_sf_review_type_politico_1` ;
ALTER TABLE `voota`.`partido` ADD COLUMN `imagen` VARCHAR(50) NULL DEFAULT NULL  AFTER `partido_id` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

