SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `voota`.`partido_i18n` ADD COLUMN `presentacion` VARCHAR(500) NULL DEFAULT NULL  AFTER `nombre` ;
ALTER TABLE `voota`.`partido` ADD COLUMN `sumd` INT(11) NOT NULL DEFAULT 0  AFTER `imagen` , ADD COLUMN `sumu` INT(11) NOT NULL DEFAULT 0  AFTER `imagen` ;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

