SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `voota`.`geo` ADD COLUMN `geo_id` INT(11) NULL DEFAULT NULL  AFTER `created_at` , 
  ADD CONSTRAINT `fk_geo_1`
  FOREIGN KEY (`geo_id` )
  REFERENCES `voota`.`geo` (`id` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
, ADD INDEX `fk_geo_1` (`geo_id` ASC) ;

ALTER TABLE `voota`.`imagen` CHANGE COLUMN `partido_id` `partido_id` INT(11) NULL DEFAULT NULL COMMENT '	'  ;

ALTER TABLE `voota`.`sf_guard_user_profile` DROP COLUMN `ACEPTA_MENSAJES` , CHANGE COLUMN `facebook_uid` `facebook_uid` VARCHAR(128) NULL DEFAULT NULL  ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

