SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `voota`.`imagen` CHANGE COLUMN `partido_id` `partido_id` INT(11) NULL DEFAULT NULL COMMENT '	'  ;

ALTER TABLE `voota`.`sf_guard_user_profile` ADD COLUMN `numero_socio` VARCHAR(45) NULL DEFAULT NULL  AFTER `mails_seguidor` ;
ALTER TABLE `voota`.`sf_guard_user_profile` DROP COLUMN `clave` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

