SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

USE `voota`;

CREATE  TABLE IF NOT EXISTS `voota`.`propuesta` (
  `id` INT(11) NOT NULL ,
  `titulo` VARCHAR(150) NULL DEFAULT NULL ,
  `descripcion` VARCHAR(600) NULL DEFAULT NULL ,
  `culture` VARCHAR(7) NULL DEFAULT NULL ,
  `sf_guard_user_id` INT(11) NOT NULL ,
  `imagen` VARCHAR(50) NULL DEFAULT NULL ,
  `doc` VARCHAR(50) NULL DEFAULT NULL ,
  PRIMARY KEY (`id`) ,
  INDEX `fk_propuesta_1` (`sf_guard_user_id` ASC) ,
  CONSTRAINT `fk_propuesta_1`
    FOREIGN KEY (`sf_guard_user_id` )
    REFERENCES `voota`.`sf_guard_user` (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;

ALTER TABLE `voota`.`propuesta` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT  ;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

