SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `voota`.`eleccion_i18n` ADD COLUMN `nombre_corto` VARCHAR(45) NULL DEFAULT NULL  AFTER `descripcion` ;

ALTER TABLE `voota`.`eleccion` CHANGE COLUMN `nombre_corto` `vanity` VARCHAR(45) NOT NULL  
, ADD UNIQUE INDEX `uniq_eleccion` (`vanity` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

