SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `voota`.`politico` CHANGE COLUMN `sf_guard_user_profile_id` `sf_guard_user_id` INT(11) NULL DEFAULT NULL  , DROP FOREIGN KEY `fk_usuario` ;

ALTER TABLE `voota`.`politico` 
  ADD CONSTRAINT `fk_usuario`
  FOREIGN KEY (`sf_guard_user_id` )
  REFERENCES `voota`.`sf_guard_user` (`id` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
, DROP INDEX `fk_usuario` 
, ADD INDEX `fk_usuario` (`sf_guard_user_id` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

