SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `voota`.`sf_guard_user_profile` DROP COLUMN `acepta_mensajes` , ADD COLUMN `email_hash` VARCHAR(255) NULL DEFAULT NULL  AFTER `numero_socio` , ADD COLUMN `email` VARCHAR(255) NULL DEFAULT NULL  AFTER `numero_socio` , ADD COLUMN `facebook_uid` INT(4) NULL DEFAULT NULL  AFTER `numero_socio` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

